# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kirma_penceresi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def __init__(self):
        super().__init__()
        self.setObjectName("Dialog")

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1028, 737)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(330, 20, 401, 41))
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 60, 321, 41))
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 100, 201, 21))
        self.label.setObjectName("label")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox.setGeometry(QtCore.QRect(250, 100, 62, 22))
        self.doubleSpinBox.setMouseTracking(True)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 130, 201, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(40, 160, 131, 21))
        self.label_5.setObjectName("label_5")
        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setGeometry(QtCore.QRect(180, 160, 61, 22))
        self.spinBox.setMouseTracking(True)
        self.spinBox.setMaximum(90)
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_2.setGeometry(QtCore.QRect(180, 190, 61, 22))
        self.spinBox_2.setMouseTracking(True)
        self.spinBox_2.setMaximum(100)
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(40, 190, 141, 21))
        self.label_6.setObjectName("label_6")
        self.spinBox_4 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_4.setGeometry(QtCore.QRect(180, 220, 61, 22))
        self.spinBox_4.setMouseTracking(True)
        self.spinBox_4.setMaximum(100)
        self.spinBox_4.setObjectName("spinBox_4")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(40, 220, 141, 21))
        self.label_8.setObjectName("label_8")
        self.spinBox_3 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_3.setGeometry(QtCore.QRect(190, 130, 61, 22))
        self.spinBox_3.setMouseTracking(True)
        self.spinBox_3.setMaximum(90)
        self.spinBox_3.setObjectName("spinBox_3")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(30, 240, 321, 41))
        self.label_7.setTextFormat(QtCore.Qt.RichText)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(40, 280, 191, 21))
        self.label_9.setObjectName("label_9")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(230, 280, 62, 22))
        self.doubleSpinBox_2.setMouseTracking(True)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(40, 310, 201, 21))
        self.label_10.setObjectName("label_10")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(170, 310, 62, 22))
        self.doubleSpinBox_3.setMouseTracking(True)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(30, 330, 351, 41))
        self.label_11.setTextFormat(QtCore.Qt.RichText)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(40, 370, 251, 21))
        self.label_12.setObjectName("label_12")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(290, 370, 62, 22))
        self.doubleSpinBox_4.setMouseTracking(True)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(30, 390, 351, 41))
        self.label_14.setTextFormat(QtCore.Qt.RichText)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(40, 420, 331, 41))
        self.label_15.setTextFormat(QtCore.Qt.RichText)
        self.label_15.setObjectName("label_15")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(60, 460, 261, 21))
        self.label_13.setObjectName("label_13")
        self.spinBox_5 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_5.setGeometry(QtCore.QRect(330, 460, 61, 22))
        self.spinBox_5.setMouseTracking(True)
        self.spinBox_5.setMaximum(10000000)
        self.spinBox_5.setObjectName("spinBox_5")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(60, 490, 301, 21))
        self.label_16.setObjectName("label_16")
        self.spinBox_6 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_6.setGeometry(QtCore.QRect(370, 490, 111, 22))
        self.spinBox_6.setMouseTracking(True)
        self.spinBox_6.setMaximum(999999999)
        self.spinBox_6.setObjectName("spinBox_6")
        self.spinBox_7 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_7.setGeometry(QtCore.QRect(360, 520, 101, 22))
        self.spinBox_7.setMouseTracking(True)
        self.spinBox_7.setMaximum(999999999)
        self.spinBox_7.setObjectName("spinBox_7")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(60, 520, 301, 21))
        self.label_17.setObjectName("label_17")
        self.spinBox_8 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_8.setGeometry(QtCore.QRect(370, 610, 111, 22))
        self.spinBox_8.setMouseTracking(True)
        self.spinBox_8.setMaximum(999999999)
        self.spinBox_8.setObjectName("spinBox_8")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(60, 640, 301, 21))
        self.label_18.setObjectName("label_18")
        self.spinBox_9 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_9.setGeometry(QtCore.QRect(360, 640, 101, 22))
        self.spinBox_9.setMouseTracking(True)
        self.spinBox_9.setMaximum(999999999)
        self.spinBox_9.setObjectName("spinBox_9")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(60, 610, 311, 21))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(40, 540, 331, 41))
        self.label_21.setTextFormat(QtCore.Qt.RichText)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(410, 460, 201, 21))
        self.label_22.setObjectName("label_22")
        self.spinBox_11 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_11.setGeometry(QtCore.QRect(540, 460, 61, 22))
        self.spinBox_11.setMouseTracking(True)
        self.spinBox_11.setMaximum(100000)
        self.spinBox_11.setObjectName("spinBox_11")
        self.spinBox_12 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_12.setGeometry(QtCore.QRect(540, 580, 61, 22))
        self.spinBox_12.setMouseTracking(True)
        self.spinBox_12.setAutoFillBackground(False)
        self.spinBox_12.setWrapping(False)
        self.spinBox_12.setMaximum(10000000)
        self.spinBox_12.setObjectName("spinBox_12")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(60, 580, 261, 21))
        self.label_19.setObjectName("label_19")
        self.spinBox_10 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_10.setGeometry(QtCore.QRect(330, 580, 61, 22))
        self.spinBox_10.setMouseTracking(True)
        self.spinBox_10.setMaximum(10000000)
        self.spinBox_10.setObjectName("spinBox_10")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(410, 580, 121, 21))
        self.label_23.setMouseTracking(True)
        self.label_23.setObjectName("label_23")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(500, 700, 93, 28)) 
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.hesapla_fonksiyonu)

        self.outputBox = QtWidgets.QPlainTextEdit(Dialog)
        self.outputBox.setGeometry(QtCore.QRect(625, 150, 350, 400))  
        self.outputBox.setReadOnly(True)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        


        self.outputBox = QtWidgets.QPlainTextEdit(Dialog)
        self.outputBox.setGeometry(QtCore.QRect(625, 150, 350, 400))  # Konum ve boyut ayarlanır.
        self.outputBox.setReadOnly(True)

        self.retranslateUi(Dialog)
        
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    

    def hesapla_fonksiyonu(self):
        iri_tuvenan_cevher_yogunlugu = self.doubleSpinBox.value()
        kabarma_faktoru = 1.5  # Kabarma faktörünün değeri burada sabit alınmıştır.
        bulk_yogunluk = iri_tuvenan_cevher_yogunlugu / kabarma_faktoru
        self.outputBox.appendPlainText(f"Kabarma Faktörü: {kabarma_faktoru} kabul edilmiştir.")
        self.outputBox.appendPlainText(f"Bulk Yoğunluğu: {bulk_yogunluk} ton/m3 bulunmuştur.")
        # Kırma Tesisinin bir haftalık ihtiyacını belirleyecek değeri ve hesaplamalarını burada yapınız.
        
        
    
        # Bir adet stok sahasının hacmini hesapla
        
        stok_sev_acisi = self.spinBox_7.value()  # Bu spinBox'ın stok şev açısını temsil ettiğini varsayıyorum. Gerekirse düzeltmelisiniz.
        stok_yuksekligi = self.spinBox_8.value()  # Bu spinBox'ın stok yüksekliğini temsil ettiğini varsayıyorum. Gerekirse düzeltmelisiniz.
        stok_uzunlugu = self.spinBox_9.value()  # Bu spinBox'ın stok uzunluğunu temsil ettiğini varsayıyorum. Gerekirse düzeltmelisiniz.

        # Hesaplama için tanımlar
        a = stok_yuksekligi
        c = stok_sev_acisi

        # Hesaplama
        ac_total = (4 * (a - c) / 2) + 4 * c  # Bu formülün doğru olduğunu varsayıyorum. Gerekirse düzeltmelisiniz.
        ac_total = bir_adet_stok_sahasi_hacmi / stok_uzunlugu  # Formülün son kısmını ekliyoruz.

        self.outputBox.appendPlainText(f"a + c = {ac_total}")

        # Üst taban ve yayılım uzunlukları
        stok_ust_taban_uzunlugu = ac_total * 0.25  # %25'ini al
        stok_yayilim_uzunlugu = ac_total * 0.75  # %75'ini al

        # Sonuçları output'a ekleyin
        self.outputBox.appendPlainText(f"Stok üst taban uzunluğu: {stok_ust_taban_uzunlugu}")
        self.outputBox.appendPlainText(f"Stok yayılım uzunluğu: {stok_yayilim_uzunlugu}")    
    
        T = self.hourly_capacity  # Saatlik Tesis Kapasitesi
        C = self.spinBox_11.value()  # Bu spinBox'ın Teorik elek altı miktarını temsil ettiğini varsayıyorum. Gerekirse düzeltmelisiniz.
        E = self.spinBox_12.value()  # Bu spinBox'ın eleme verimini temsil ettiğini varsayıyorum. Gerekirse düzeltmelisiniz.

        # K değerini hesapla
        K = T * (1 - C * E)

        # Sonuçları output'a ekleyin
        self.outputBox.appendPlainText(f"K = {K} ton/saat Kırıcıya giren malzeme miktarı olarak bulunur.")

        a = self.spinBox_13.value()  # Kapalı devrede elek üstü miktarını temsil ettiğini varsayıyorum. Gerekirse düzeltmelisiniz.
        b = 0.14  # Kırıcıdan çıkan malzemenin öngörülen kırma boyutundan daha iri malzeme miktarı 
        T = self.hourly_capacity  # Tesis Kapasitesi
        E = 0.85  # eleme verimi

        # Değerlerin kabul edildiğini belirt
        self.outputBox.appendPlainText(f"Kırıcıdan çıkan malzemenin öngörülen kırma boyutundan daha iri malzeme miktarı {b} olarak kabul edilmiştir.")
        self.outputBox.appendPlainText(f"Eleme verimi {E} olarak kabul edilmiştir.")

        # R değerini hesapla
        R = T * (a / (1 - (b / E)))

        # Sonuçları output'a ekleyin
        self.outputBox.appendPlainText(f"Devreden yük {R} ton/saat kırıcıya giren malzeme miktarı olarak bulunur.")

        beslenen_malzeme_miktari = self.spinBox_14.value()  # Beslenen Malzeme Miktarını temsil ettiğini varsayıyorum. Gerekirse düzeltmelisiniz.
        cikis_acikligi = self.spinBox_15.value()  # Çıkış Açıklığı'nı temsil ettiğini varsayıyorum. Gerekirse düzeltmelisiniz.
        Wi = 12.49  # Kabullenilen değer
        D1 = self.spinBox_16.value()  # Kırıcıya beslenen malzemenin d80‟i
        D2 = self.spinBox_17.value()  # Kırıcıdan çıkan malzemenin d80‟i
        K_emniyet = 1.25  # Kabullenilen değer

        # Değerlerin kabul edildiğini belirt
        self.outputBox.appendPlainText(f"Wi: {Wi} olarak kabul edilmiştir.")
        self.outputBox.appendPlainText(f"K_emniyet: {K_emniyet} olarak kabul edilmiştir.")

        # Wt değerini hesapla
        Wt = 10 * Wi * ((1 / (D2 ** 0.5)) - (1 / (D1 ** 0.5)))

        # Sonucu output'a ekleyin
        self.outputBox.appendPlainText(f"Wt = {Wt} kWh/ton olarak bulunmuştur.")

        # Güç değerini hesapla
        guc = beslenen_malzeme_miktari * Wt * K_emniyet 

        # Sonucu output'a ekleyin
        self.outputBox.appendPlainText(f"Güç = {guc} kW olarak bulunmuştur.")

        # Güç değerini HP'ye dönüştür ve sonucu output'a ekleyin
        guc_hp = guc * 1.341
        self.outputBox.appendPlainText(f"Güç = {guc_hp} HP olarak bulunmuştur.")


    
        

        
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:700;\">KIRICI SEÇİMİ VE HESAPLAMALARI</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-family:\'Times New Roman,Bold\'; font-size:12pt; font-weight:700;\">1.1 İri Cevher Stok Sahası Tasarımı ve Boyutlandırması </span></p></body></html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">İri Tüvenan Cevher Yoğunluğu (ton/m3): </span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Stok alanı sayısını giriniz:</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Stok şev açısını giriniz:</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Stok yüksekliğini giriniz:</span></p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Stok uzunluğunu giriniz:</span></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-family:\'Times New Roman,Bold\'; font-size:12pt; font-weight:700;\">1.2 Birinci Kademe Kırma Çeneli Kırıcı Yük Hesabı </span></p></body></html>"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p>Teorik elek altı miktarını giriniz: </p></body></html>"))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Eleme verimini giriniz:</span></p></body></html>"))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-family:\'Times New Roman,Bold\'; font-size:12pt; font-weight:700;\">1.2 İ</span><span style=\" font-family:\'Times New Roman,Bold\'; font-size:12pt; font-weight:700;\">kinci Kademe Kırma Konili Kırıcı Devreden Yük Hesabı </span></p></body></html>"))
        self.label_12.setText(_translate("Dialog", "<html><head/><body><p>Kapalı devrede elek üstü miktarını giriniz:</p></body></html>"))
        self.label_14.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-family:\'Times New Roman,Bold\'; font-size:12pt; font-weight:700;\">1.3 </span><span style=\" font-family:\'Times New Roman,Bold\'; font-size:12pt; font-weight:700;\">Kırıcıların Güç Hesapları ve Seçimi </span></p></body></html>"))
        self.label_15.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-family:\'Times New Roman,Bold\'; font-size:12pt; font-weight:700;\">1.3.1 Primer Çeneli Kırıcı Güç Hesabı</span></p></body></html>"))
        self.label_13.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Beslenen malzeme miktarını giriniz (ton/saat):</span></p></body></html>"))
        self.label_16.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-family:\'Times New Roman\';\">D1 : Kırıcıya beslenen malzemenin d80\'i giriniz (mikron):</span></p></body></html>"))
        self.label_17.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-family:\'Times New Roman\';\">D2 : Kırıcıdan çıkan malzemenin d80\'i giriniz (mikron):</span></p></body></html>"))
        self.label_18.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-family:\'Times New Roman\';\">D2 : Kırıcıdan çıkan malzemenin d80\'i giriniz (mikron):</span></p></body></html>"))
        self.label_20.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-family:\'Times New Roman\';\">D1 : Kırıcıya beslenen malzemenin d80\'i giriniz (mikron):</span></p></body></html>"))
        self.label_21.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-family:\'Times New Roman,Bold\'; font-size:12pt; font-weight:700;\">1.3.2 Sekonder Çeneli Kırıcı Güç Hesabı</span></p></body></html>"))
        self.label_22.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Çıkış açıklığını giriniz:</span></p></body></html>"))
        self.label_19.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Beslenen malzeme miktarını giriniz (ton/saat):</span></p></body></html>"))
        self.label_23.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Çıkış açıklığını giriniz:</span></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "Hesapla"))
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
