# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ui_kirma_penceresi import Ui_Dialog  # ui_kirma_penceresi.py dosyasından sınıfı import edin



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(470, 271)
        MainWindow.setMaximumSize(QtCore.QSize(800, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBoxStockpiling = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxStockpiling.setAutoFillBackground(False)
        self.checkBoxStockpiling.setObjectName("checkBoxStockpiling")
        self.gridLayout.addWidget(self.checkBoxStockpiling, 7, 0, 1, 1)
        self.checkBoxEnrichment = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxEnrichment.setAutoFillBackground(False)
        self.checkBoxEnrichment.setObjectName("checkBoxEnrichment")
        self.gridLayout.addWidget(self.checkBoxEnrichment, 5, 0, 1, 1)
        self.checkBoxGrinding = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxGrinding.setMaximumSize(QtCore.QSize(782, 21))
        self.checkBoxGrinding.setAutoFillBackground(False)
        self.checkBoxGrinding.setObjectName("checkBoxGrinding")
        self.gridLayout.addWidget(self.checkBoxGrinding, 3, 0, 1, 1)
        self.checkBoxScreening = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxScreening.setAutoFillBackground(False)
        self.checkBoxScreening.setObjectName("checkBoxScreening")
        self.gridLayout.addWidget(self.checkBoxScreening, 1, 0, 1, 1)
        self.checkBoxCrushing = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxCrushing.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxCrushing.setAutoFillBackground(False)
        self.checkBoxCrushing.setIconSize(QtCore.QSize(20, 20))
        self.checkBoxCrushing.setObjectName("checkBoxCrushing")
        self.gridLayout.addWidget(self.checkBoxCrushing, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.kirma_penceresi_ac)  # Hesapla düğmesi tıklandığında kirma_penceresi_ac fonksiyonu çağrılır
        self.gridLayout.addWidget(self.pushButton, 8, 0, 1, 0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def kirma_penceresi_ac(self):
        if self.checkBoxCrushing.isChecked():  
            self.kirma_window = QtWidgets.QMainWindow()  
            self.ui = Ui_Dialog()  
            self.ui.setupUi(self.kirma_window)  
            self.kirma_window.show()  

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBoxStockpiling.setText(_translate("MainWindow", "Stoklama"))
        self.checkBoxEnrichment.setText(_translate("MainWindow", "Zenginleştirme"))
        self.checkBoxGrinding.setText(_translate("MainWindow", "Öğütme"))
        self.checkBoxScreening.setText(_translate("MainWindow", "Eleme"))
        self.checkBoxCrushing.setText(_translate("MainWindow", "Kırma"))
        self.pushButton.setText(_translate("MainWindow", "Hesapla"))
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 0, 0, 1)
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
